//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppliFraisWebService.BaseDonne
{
    using System;
    using System.Collections.Generic;
    
    public partial class etat
    {
        public etat()
        {
            this.fichefrais = new HashSet<fichefrais>();
        }
    
        public string id { get; set; }
        public string libelle { get; set; }
    
        public virtual ICollection<fichefrais> fichefrais { get; set; }
    }
}
