//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppliFraisWebService.BaseDonne
{
    using System;
    using System.Collections.Generic;
    
    public partial class fichefrais
    {
        public fichefrais()
        {
            this.lignefraisforfait = new HashSet<lignefraisforfait>();
            this.lignefraishorsforfait = new HashSet<lignefraishorsforfait>();
        }
    
        public string idVisiteur { get; set; }
        public string mois { get; set; }
        public Nullable<int> nbJustificatifs { get; set; }
        public Nullable<decimal> montantValide { get; set; }
        public Nullable<System.DateTime> dateModif { get; set; }
        public string idEtat { get; set; }
    
        public virtual etat etat { get; set; }
        public virtual visiteur visiteur { get; set; }
        public virtual ICollection<lignefraisforfait> lignefraisforfait { get; set; }
        public virtual ICollection<lignefraishorsforfait> lignefraishorsforfait { get; set; }
    }
}
