//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppliFraisWebService.BaseDonne
{
    using System;
    using System.Collections.Generic;
    
    public partial class fraisforfait
    {
        public fraisforfait()
        {
            this.lignefraisforfait = new HashSet<lignefraisforfait>();
        }
    
        public string id { get; set; }
        public string libelle { get; set; }
        public Nullable<decimal> montant { get; set; }
    
        public virtual ICollection<lignefraisforfait> lignefraisforfait { get; set; }
    }
}
