//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppliFraisWebService.BaseDonne
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gsb_fraisEntities : DbContext
    {
        public gsb_fraisEntities()
            : base("name=gsb_fraisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<etat> etat { get; set; }
        public DbSet<fichefrais> fichefrais { get; set; }
        public DbSet<fraisforfait> fraisforfait { get; set; }
        public DbSet<lignefraisforfait> lignefraisforfait { get; set; }
        public DbSet<lignefraishorsforfait> lignefraishorsforfait { get; set; }
        public DbSet<visiteur> visiteur { get; set; }
    }
}
